### ISSUE TITLE
Example of using autofac in a unit test project

### ISSUE THREAD

**Issue by johnnyreilly** [autofac/Examples#1]
Hi,

First of all, great work on Autofac - I love it!  

I was just browsing through your examples and noticed there isn't an example of how autofac is best used in an integration test project.  Is there any suggested guidance on how best to go about this?

In a current project I have this inheritance-based approach which I knocked up in a hurry:

```
using System;
using System.Diagnostics;
using System.Reflection;
using Autofac;
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace SomeTests
{
    public class TestBase 
    {
        private IContainer _autofacContainer;
        protected IContainer AutofacContainer
        {
            get
            {
                if (_autofacContainer == null)
                {
                    var builder = new ContainerBuilder();

                    // Repositories
                    builder.RegisterType<CompanyDataDb>().As<CompanyDataDb>().InstancePerLifetimeScope();

                    // Register the CompanyDataRepository for property injection not constructor allowing circular references
                    builder.RegisterType<CompanyDataRepository>().As<ICompanyDataRepository>()
                           .InstancePerLifetimeScope()
                           .PropertiesAutowired(PropertyWiringOptions.AllowCircularDependencies);

                    // Other wireups....

                    var container = builder.Build();

                    _autofacContainer = container;
                }

                return _autofacContainer;
            }
        }

        protected ICompanyDataRepository CompanyDataRepository
        {
            get
            {
                return AutofacContainer.Resolve<ICompanyDataRepository>();
            }
        }

        protected CompanyDataDb CompanyDataDb
        {
            get
            {
                return AutofacContainer.Resolve<CompanyDataDb>();
            }
        }
    }
}
```

All the tests inherit from this class.  This works but I kind of doubt it's a good example of good practice - is there a better example out there I could refer to?

**Comment by tillig** [comment]
I think the challenge here will be that how you use Autofac in your tests (_if_ you use Autofac in your tests) is going to be very application-specific and is going to depend on the type of tests you're writing.

By way of example, I have several work projects where we have literally thousands of unit tests. To construct one of the objects under test (create the mock objects, pass them into the constructor, return a constructed object with mock dependencies) I generally use a static method in the test fixture rather than wiring up a fixture-level container and resolving.

On the other hand, if you have an MVC app and need to do something that requires you to fake a per-request lifetime scope (like you do service location in the middle of a method), [we actually have some docs on that](http://autofac.readthedocs.org/en/latest/faq/per-request-scope.html#testing-with-per-request-dependencies).

Or if what you're writing is a set of integration tests rather than unit tests - where you actually want to create a "real" stack of things and test the interaction between them rather than just testing a single class unit-test-style - then the way you'd set up the container would sort of depend on how your integration tests are driven. Like if you're self-hosting a Web API endpoint, you'd probably set up the Autofac container around the same time you set up the self-hosted endpoint, just before starting to listen for requests.

Things also may depend on the test framework and how you write tests and/or pass around context. Some folks love using a static `TestContext.Current` style thing; others like using instance variables on the test fixture.

As you can see, it's hard to provide examples beyond our own unit tests in the various repos; and it's even harder to provide "guidance" of any nature... which is why we don't have example unit tests.

Looking at your specific test code, it appears you are writing some sort of integration test, since it also appears you're wiring up a lot more than just fakes to unit test a particular class. If that setup works for you, awesome. The only thing I, personally, might do different is refactor the logic into a separate class since I, personally, am not a fan of base classes or inheritance around test fixtures if it can be avoided. That said, it's totally a personal preference, and if this works for you, all the better.

**Comment by johnnyreilly** [comment]
Thanks for the feedback - clearly lots to think about.  I wonder if it might be worth highlighting in your docs that you are intentionally not providing unit test examples for the reasons you've stated?  Might save other people from raising the issue I just did.

On the last point I'm also not a massive fan of base classes / inheritance in this particular scenario either - this was code written at speed which I'm looking at refactoring much in the manner you suggest at present.

Thanks again.
