### ISSUE TITLE
AutofacModule Load(...) method has outdated comment

### ISSUE THREAD

**Issue by dchennells** [autofac/Examples#12]
In the master branch, the Load method in the AutofacModule has a comment that reflects a previous configuration, namely:

> The generic ILogger<TCategoryName> service was added to the ServiceCollection by ASP.NET Core.  It was then registered with Autofac using the Populate method in ConfigureServices.

However, the current Startup.cs reflects the following method signature:
`void ConfigureContainer(ContainerBuilder builder)`
`void ConfigureServices(IServiceCollection services)`

The latter method does not include the previously specified Populate() call.

You might want to change the comment to acknowledge that, on the contrary, none of the IServiceCollection services are available to be resolved until the startup configuration has completed (well after the Module.Load() implementation call).

The good news is that actual DI (such as to controller constructors) is of course still resolving fine with the module pattern.  A problem arises if someone trusts the comment and attempts in the context of debugging/experimentation to build the container and try to resolve IValuesService within the load method, similar to what is in numerous examples in the manual.  (This problem does not exist with the alternative pattern of the Populate(IServiceCollection services) call prior to adding Autofac.builder registrations.)

You might consider shifting registration of the logger in your sample to the Load method (i.e. to the Autofac container) so that it is available for casual experimentation.  Alternatively, to change the example to eliminate the dependency of the ValuesService on ILogger<>, though that is one of the core scenarios.

**Comment by dchennells** [comment]
When you say in your revised comment:

> It was then registered with Autofac using the Populate method.

where do you mean?  I don't see that call in the user code (i.e. in the sample).

The much older pattern did have that call.  For example, see this block in the eShop [Startup.cs](https://github.com/dotnet-architecture/eShopOnContainers/blob/a387f21029f0b2d49614d165d5384717d2398f8e/src/Services/Payment/Payment.API/Startup.cs)

`var container = new ContainerBuilder();
 container.Populate(services);
 return new AutofacServiceProvider(container.Build());
`

The change in pattern has an effect on diagnostic/debugging code (though not, of course, on actual DI).

For example, you can't put **in the body of the Load method (as you are experimenting with Autofac, following along with the docs)**:

`            builder.Register(c => new ValuesService(c.Resolve<ILogger<ValuesService>>()))
                .As<IValuesService>()
                .InstancePerLifetimeScope();

            // Build the container to finalize registrations
            // and prepare for object resolution.
            var container = builder.Build();

            // Now you can resolve services using Autofac. For example,
            // this line will execute the lambda expression registered
            // to the IConfigReader service.
            using (var scope = container.BeginLifetimeScope())
            {
                var valuesService = scope.Resolve<IValuesService>();
            }`

That throws the following exception:

> "The requested service 'Microsoft.Extensions.Logging.ILogger`1[[Assiduo.PI.Server.WebServices.ServiceRegistration.ValuesService, Assiduo.PI.Server.WebServices, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]' has not been registered. To avoid this exception, either register a component to provide the service, check for service registration using IsRegistered(), or use the ResolveOptional() method to resolve an optional dependency."

And the reason is almost certainly because **Populate has not been called prior to the Load call**. (Note that the same code runs fine using the much older pattern above in the eShop example.)

(All of the dependencies are of course available to be resolved later, when the lambda expressions are actually normally invoked, at the time of DI or scoped resolution, *after* service registration.)

You might want to think about taking out the reference to the Populate method that you've left in the comment in the Load method.  I believe it is incorrect.

Incidentally, you're welcome for the help and contribution here.  ;)

**Comment by tillig** [comment]
You have to read the whole comment:

> It was then registered with Autofac using the Populate method. All of this starts
> with the services.AddAutofac() that happens in Program and registers Autofac
> as the service provider.

Unfortunately, there is actually a lot of complexity that the ASP.NET Core framework adds with its automatic setup that isn't really practical to document in a comment. You have to go look at actual source in Autofac (sorry) to get clarification.

- [`services.AddAutofac()` adds an `IServiceProviderFactory<ContainerBuilder>`](https://github.com/autofac/Autofac.Extensions.DependencyInjection/blob/36d487749ef7184357bbc4d162bf425b8474eb36/src/Autofac.Extensions.DependencyInjection/ServiceCollectionExtensions.cs#L44) to the services collection.
- A lot of [very, very complex startup logic in ASP.NET Core](https://github.com/aspnet/AspNetCore/blob/a16a6dfaeb52cda2b853ba46c75fc96d56f24e00/src/Hosting/Hosting/src/Internal/StartupLoader.cs) runs to figure out things like whether there's a provider factory or not; whether there's more than one service configuration method or not; and so on.
- Eventually the startup logic calls the [`CreateBuilder` method on the provider factory where, in fact, `Populate` is called for you](https://github.com/autofac/Autofac.Extensions.DependencyInjection/blob/36d487749ef7184357bbc4d162bf425b8474eb36/src/Autofac.Extensions.DependencyInjection/AutofacServiceProviderFactory.cs#L56).

However, all of that is:

1. Really complicated, so much so that putting it into an _example_ really isn't practical. The Examples complement the documentation, [where we walk through this in much more depth](https://docs.autofac.org/en/latest/integration/aspnetcore.html).
2. Actually changing all the time, like the way things happen in ASP.NET Core 2.0 is pretty different than ASP.NET Core 1.0, and the 3.0 stuff is going to obsolete the way things are done in 2.0 in some cases, so... being 100% accurate for all versions in all examples in all documentation also isn't practical.

eShop isn't something we own, support, test against, or validate works. If you're having trouble following along docs and doing things in that solution, that's something you will have to take up with those folks. Our `AutofacModule.Load` method, at the time of this writing, does not call `Populate` and in neither our sample nor our documentation do we ever show that happening (that I'm aware of).

The reference to `Populate` is important in the module because most users of Autofac recognize that you have to explicitly register everything you want resolved. We received early feedback that having the module resolve an `ILogger` without explaining how it got registered is _also_ unclear. But, as you say, it's not in user code directly, so I hoped to clarify that.

Sorry for the confusion. If you think you can word it in a better way that can satisfy:

- The module explains how `ILogger` got registered so users don't wonder where the explicit Autofac registration for that is
- The explanation is not so long that people hit "TLDR" level and continue asking questions about it because they skipped over it
- The explanation doesn't have to be constantly maintained and updated as ASP.NET Core changes the way it handles things

...then I'm totally open to pull requests. Otherwise, this is about the best we can do.

**Comment by dchennells** [comment]
One quick and dispositive way to determine whether the "Eventually" (in your comment) is in fact prior to or after Load is called, would be to debug the Autofac.Extensions.DependencyInjection source project in the Asp NET Core Example solution (and reference the project, not the package).

If one were to do that, and to put a breakpoint on the lines in the `AutofacServiceProviderFactory` with 

`builder.Populate(services);`

and another one on the first line of code in the Load method, which breakpoint would get hit first?

Once we establish that it will become more clear whether to use the past or the future tense in the comment in the Load method in referring to the calling of Populate().
