### ISSUE TITLE
MSB4126 error when executing dotnet restore

### ISSUE THREAD

**Issue by Legends** [autofac/Examples#6]
Error when hitting **dotnet restore**
> C:\Users\Admin\Source\Repos\Examples\Examples.sln.metaproj : error MSB4126: The specified solution configuration "Debug|X64" is invalid. Please specify a valid solution configuration using the Configuration and Platform properties (e.g. MSBuild.exe Solution.sln /p:Configuration=Debug /p:Platform="Any CPU") or leave those properties blank to use the default solution configuration. [C:\Users\Admin\Source\Repos\Examples\Examples.sln] 

When I try to build the solution, MVC and Webform projects are unavailable and EnterpriseLibraryExample.MvcApplication has missing references.   

.NET Command Line Tools (2.1.2)

Product Information:
 Version:            2.1.2
 Commit SHA-1 hash:  5695315371

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.2\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.3
  Build    : a9190d4a75f4a982ae4b4fa8d1a24526566c69df

**Comment by tillig** [comment]
Updated to use the latest VS build tools.

**Comment by Legends** [comment]
What's the solution?

**Comment by tillig** [comment]
The solution is to update your checkout because I updated the code to use the latest VS build tools, thus removing the issue.

**Comment by tillig** [comment]
- If you cloned the GitHub repo to get the code, just do a git pull to update your checked out copy of the code ("your checkout").
- If you manually downloaded the code as a zip file instead, do a new download.

**Comment by Legends** [comment]
Ah, ok I understand, we call it "Get Latest". 
I did a new download.  But same error.

**Comment by tillig** [comment]
- Shut down all VS instances.
- Remove all your `.vs`, `bin`, and `obj` folders (or do `git clean -dfx`)
- Make sure you have all the VS patches up to current.

I can't reproduce any errors anymore and it builds fine on AppVeyor as well, so I'm not sure what more guidance I can provide. It's going to be a per-user / environment-specific problem if that doesn't fix it.

**Comment by Legends** [comment]
It's only the ASP.NET Core project that is failing....

![image](https://user-images.githubusercontent.com/966368/34499894-96e831ae-f008-11e7-9f7a-91f3c6917384.png)

**Comment by Legends** [comment]
I did what you said, but `dotnet restore` failed, I executed the build.ps1 file, you can see the result above.
Thanks for the quick support!

**Comment by tillig** [comment]
As mentioned, I can't reproduce this either on any local machine I have or on the AppVeyor continuous integration build server. That means it's something with your machine or your user account/profile on that machine that I'm not able to troubleshoot. If I can't repro it, I can't do anything further to help. Sorry.

You could try additional troubleshooting on your end. For example...
- Create a brand new ASP.NET Core web app. File => New style. Do a diff and see what's different between the example project and the file/new project you just made.
- Run `nuget` at the command prompt. It should be a really recent version, something in the 4.3 - 4.4 range. 2.x or early 3.x doesn't know how to handle package restore right.
- Do a `dotnet --version` from the command prompt. It should show 1.1.0. If it doesn't, that's a problem - it's not obeying the `global.json`.
- Did you switch your NuGet sources? The `NuGet.config` in the Examples repo points at nuget.org by default, some enterprises or devs set up their own settings.
- Clear your NuGet package cache: `nuget locals all -clear`

At this point I'm really just grasping at straws because, again, I can't reproduce the issue at all anywhere. If you still can't figure it out, consider opening a question on StackOverflow so you have a wider audience to help you - there are only maybe two people who watch this repo, one of whom is me. There are thousands of people to help you on StackOverflow.

**Comment by Legends** [comment]
I tried all the things except the Diff!

I have opened an [thread ](https://stackoverflow.com/questions/48069444/dotnet-restore-not-working)regarding this issue on SO:

**Comment by Legends** [comment]
I migrated the project to .net core 2.0 and changed the sdk to 2.1.3.
Removed all references in AspNetCoreExample manually and added the latest version for all of them.
Now it works.

**Comment by hugozr** [comment]
I solved it by canceling the environment variable Platform: SET Platform=
